name: Run Selenium Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium pytest allure-pytest webdriver-manager requests

      - name: Install Chrome and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          chrome_version=$(google-chrome --version | awk '{print $3}' | cut -d'.' -f1)
          wget https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$chrome_version -O chromedriver_version.txt
          chromedriver_version=$(cat chromedriver_version.txt)
          wget https://chromedriver.storage.googleapis.com/$chromedriver_version/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          chromedriver --version

      - name: Run tests
        run: |
          python -m pytest tests/ -v --alluredir=allure-results

      - name: Upload Allure report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: allure-report
          path: allure-results/